---
# tasks file for lighthouse-role
- name: Install nginx
  hosts: lighthouse
  gather_facts: false
  handlers:
    - name: Restart-NGINX
      ansible.builtin.service:
        name: nginx.service
        state: restarted
  tasks:
    - name: NGINX - Add repository
      become: true
      ansible.builtin.yum_repository:
        name: nginx
        description: NGINX repo
        baseurl: http://nginx.org/packages/mainline/centos/7/x86_64/
        gpgcheck: false
    - name: NGINX - Install
      become: true
      ansible.builtin.yum:
        name: nginx
        state: present
      notify: Restart-NGINX
    - name: NGINX - create config
      become: true
      ansible.builtin.template:
        src: templates/nginx.conf.j2
        dest: /etc/nginx/nginx.conf
        mode: 0644
      notify: Restart-NGINX
- name: Install lighthouse
  hosts: lighthouse
  tasks:
    - name: Install dependencies
      become: true
      ansible.builtin.yum:
        name: git
        state: present
    - name: Lighthouse - install
      become: true
      ansible.builtin.git:
        repo: 'https://github.com/VKCOM/lighthouse.git'
        version: master
        dest: "{{ lighthouse_location_dir }}"
      register: copy_remote